image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - test
  - publish

test:
  stage: test
  except:
    - tags
  script:
    - dotnet test -v minimal -c Release /p:CollectCoverage=true

publish:
  stage: publish
  only:
    - tags
  script:
    - |
      echo ---------------------------------------------- VERSIONING
      
      cd FunctionalLink.Next      
      echo VERSION := $CI_COMMIT_TAG      
      sed -i -- "s/1\.0\.0/${CI_COMMIT_TAG}/g" FunctionalLink.Next.csproj
      cd ..

      echo ---------------------------------------------- TESTING
      
      cd FunctionalLink.Next.Tests      
      dotnet test -v minimal -c Release /p:CollectCoverage=true      
      cd ..
      
      echo ---------------------------------------------- BUILDING
      
      cd FunctionalLink.Next      
      dotnet build -c Release
      
      echo ---------------------------------------------- PUBLISHING
      
      cd bin/Release      
      NUGET_PKG=$(ls *.nupkg)      
      echo PACKAGE := $NUGET_PKG    
      dotnet nuget push $NUGET_PKG -k $NUGET_KEY -s https://api.nuget.org/v3/index.json

pages:
  only:
    refs:
      - master
  dependencies:
    - test
  script:
    - cp -r ./FunctionalLink.DocFx/_site ./public
  artifacts:
    paths:
      - public
