image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet build"
    
test:
    stage: test
    script: 
        - "dotnet test"
          
pages:    
    script:        
        - "echo docfx makes me mad"
    artifacts: 
        paths: 
            - "FunctionalLink.DocFx/_site"
